clone:
  git:
    image: plugins/git
    depth: 50
    tags: true

pipeline:
  scp:
    image: appleboy/drone-scp
    host: 139.59.123.108
    username: drone
    password: 1234567890
    port: 22
    target: /home/drone
    source: /Users/archer/Desktop/drone/test.txt